# Config file for automatic testing at travis-ci.org

# Containerized builds
sudo: false

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

install:
  - pip install -U .
  - npm install -g swagger-tools
  - pip install -r dev-requirements.txt

script: invoke test
