# Config file for automatic testing at travis-ci.org

# Containerized builds
sudo: false

language: python

env:
  # Lowest supported version
  - WEBARGS_VERSION="==0.15.0"
  # Latest release
  - WEBARGS_VERSION=""

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  - pip install -U .
  - npm install -g swagger-tools
  - pip install -r dev-requirements.txt
  - pip install -U webargs"$WEBARGS_VERSION"

before_script:
  - flake8 .

script: py.test
